application: bitcoinspellbook
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:

- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /robots\.txt
  static_files: robots.txt
  upload: robots\.txt

- url: /data/block
  script: BitcoinSpellbook.app

- url: /data/latestBlock
  script: BitcoinSpellbook.app

- url: /data/prime_input_address
  script: BitcoinSpellbook.app

- url: /data/transactions
  script: BitcoinSpellbook.app

- url: /data/balances
  script: BitcoinSpellbook.app

- url: /data/utxos
  script: BitcoinSpellbook.app

- url: /data/save_provider
  script: BitcoinSpellbook.app

- url: /data/delete_provider
  script: BitcoinSpellbook.app

- url: /data/get_providers
  script: BitcoinSpellbook.app

- url: /admin/initialize
  script: BitcoinSpellbook.app
  login: admin

- url: /admin/updateRecommendedFee
  script: BitcoinSpellbook.app
  login: admin


- url: /inputs/SIL
  script: BitcoinSpellbook.app

- url: /linker/LBL
  script: BitcoinSpellbook.app

- url: /linker/LRL
  script: BitcoinSpellbook.app

- url: /linker/LSL
  script: BitcoinSpellbook.app

- url: /linker/LAL
  script: BitcoinSpellbook.app

- url: /random/proportional
  script: BitcoinSpellbook.app

- url: /random/block
  script: BitcoinSpellbook.app

- url: /voter/proposal
  script: BitcoinSpellbook.app

- url: /voter/results
  script: BitcoinSpellbook.app

- url: /forwarder/get_forwarders
  script: BitcoinSpellbook.app

- url: /forwarder/get_forwarder
  script: BitcoinSpellbook.app

- url: /forwarder/check_address
  script: BitcoinSpellbook.app

- url: /forwarder/save_forwarder
  script: BitcoinSpellbook.app

- url: /forwarder/delete_forwarder
  script: BitcoinSpellbook.app

- url: /forwarder/do_forwarding
  script: BitcoinSpellbook.app
  login: admin


- url: /distributer/get_distributers
  script: BitcoinSpellbook.app

- url: /distributer/get_distributer
  script: BitcoinSpellbook.app

- url: /distributer/check_address
  script: BitcoinSpellbook.app

- url: /distributer/save_distributer
  script: BitcoinSpellbook.app

- url: /distributer/delete_distributer
  script: BitcoinSpellbook.app


- url: /distributer/update_distribution
  script: BitcoinSpellbook.app

- url: /distributer/do_distributing
  script: BitcoinSpellbook.app
  login: admin


- url: /trigger/get_triggers
  script: BitcoinSpellbook.app

- url: /trigger/get_trigger
  script: BitcoinSpellbook.app

- url: /trigger/save_trigger
  script: BitcoinSpellbook.app

- url: /trigger/delete_trigger
  script: BitcoinSpellbook.app

- url: /trigger/save_action
  script: BitcoinSpellbook.app

- url: /trigger/delete_action
  script: BitcoinSpellbook.app


- url: /trigger/check_triggers
  script: BitcoinSpellbook.app
  login: admin



- url: /writer/get_writers
  script: BitcoinSpellbook.app

- url: /writer/get_writer
  script: BitcoinSpellbook.app

- url: /writer/save_writer
  script: BitcoinSpellbook.app

- url: /writer/delete_writer
  script: BitcoinSpellbook.app

- url: /writer/do_writing
  script: BitcoinSpellbook.app
  login: admin

- url: /profile/profile
  script: BitcoinSpellbook.app

- url: /
  script: BitcoinSpellbook.app



libraries:
- name: webapp2
  version: "2.5.2"
- name: jinja2
  version: latest
- name: pycrypto
  version: "2.6"